name: All Tests

on:
  push:
    branches: [ cole_test_actions, master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make -j6
    - name: Bedrock Tests
      run: cd test && ./test -threads 6
    - name: Cluster Tests
      run: cd test/clustertest && ./clustertest -threads 6
