name: All Tests

on:
  push:
    branches: [ cole_test_actions, master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make -j6
    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          bedrock
          test/test
          test/clustertest/clustertest
  bedrock_tests:
      runs-on: ubuntu-16.04
      needs: build
      steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
      - name: Bedrock Tests
        run: cd test && chmod +x test && ./test -threads 6
  cluster_tests:
      runs-on: ubuntu-16.04
      needs: build
      steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
      - name: Cluster Tests
        run: cd test/clustertest && chmod +x clustertest && ./clustertest -threads 6  
